"
# SWRegularExpression

I contain the classes of a regular expression state machine.

## Reference

My design is based of the course [Automata: building a regexp machine] (https://www.udemy.com/course/automata-theory-building-a-regexp-machine/?src=sac&kw=automata)
available from Udemy.

## Package Prefix

Packages and classes are prefixed with `SW` for the initials of the author
Samuel Wilson.
"
Class {
	#name : #ManifestSWRegularExpression,
	#superclass : #PackageManifest,
	#category : #'SWRegularExpression-Manifest'
}
